site_name: Plugin Developer Course
site_description: Comprehensive onboarding for Plugin Developers at weDevs
site_author: weDevs
site_url: https://getdokan.github.io/plugin-developer-course

# Repository
repo_name: getdokan/plugin-developer-course
repo_url: https://github.com/getdokan/plugin-developer-course
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 weDevs

# Theme configuration
theme:
  name: material
  language: en
  
  # Color palette
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # Font
  font:
    text: Roboto
    code: Roboto Mono
  
  # Features
  features:
    - navigation.instant        # Instant loading
    - navigation.tracking       # Anchor tracking
    - navigation.tabs          # Top-level sections as tabs
    - navigation.tabs.sticky   # Sticky tabs
    - navigation.sections      # Section navigation
    - navigation.expand        # Expand navigation by default
    - navigation.path          # Show path breadcrumbs
    - navigation.top           # Back to top button
    - navigation.footer        # Footer navigation
    - search.suggest           # Search suggestions
    - search.highlight         # Highlight search results
    - search.share            # Share search results
    - toc.follow              # TOC follows scroll
    - toc.integrate           # Integrate TOC with navigation
    - content.code.copy       # Copy code button
    - content.code.annotate   # Code annotations
    - content.action.edit     # Edit this page button
    - content.action.view     # View source button
  
  # Icon
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye
  
  # Logo
  logo: assets/favicon.png
  favicon: assets/favicon.png

# Plugins
plugins:
  - search:
      lang: en
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - tags:
      tags_file: tags.md

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      permalink_title: Anchor link to this section
  
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree navigation
nav:
  - Home:
    - Welcome: index.md
    - Quick Start: QUICK-START.md
    - Onboarding Guide: ONBOARDING-GUIDE.md
  
  - Programming Languages:
    - Overview: programming-languages/index.md
    - Setup: programming-languages/dev-environment.md
    - HTML & CSS: programming-languages/HtmlCss.md
    - JavaScript: programming-languages/JavaScript.md
    - PHP & MySQL: programming-languages/PhpMysql.md
  
  - Operating System:
    - OS Fundamentals: operating-system/os-fundamentals.md
  
  - Web Fundamentals:
    - Web Basics: web-fundamentals/web-basics.md

  - WordPress Development:
    - Overview: wordpress/index.md
    - Introducing WordPress: wordpress/02-introducing-wordpress.md
    - Coding Conventions: wordpress/03-coding-conventions.md
    - Basic Plugin Development: wordpress/04-basic-plugin-development.md
    - REST API: wordpress/06-rest-api.md
    - Basic Theme Development: wordpress/05-basic-theme-development.md
    - WP-CLI: wordpress/07-wp-cli.md

  - Reference:
    - Debugging Setup: debuging.md
    - Progress Checklist: PROGRESS-CHECKLIST.md
    - Course Links: COURSE-LINKS.md
    - Summary: SUMMARY.md
    - Changelog: CHANGELOG.md

# Extra configuration
extra:
  # Social links
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/getdokan
      name: GitHub
    - icon: fontawesome/solid/globe
      link: https://wedevs.com
      name: weDevs Website
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/weDevs
      name: Twitter
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/wedevs
      name: Facebook
  
  # Version
  version:
    provider: mike
  
  # Analytics (optional - uncomment and add your ID)
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX
  
  # Consent (GDPR)
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

# Additional CSS (optional)
# extra_css:
#   - stylesheets/extra.css

# Additional JavaScript (optional)
# extra_javascript:
#   - javascripts/extra.js

